name: 'Generate Arch Repo database'
inputs:
  repo_name:
    required: true
  gpg-privatekey:
    description: 'Your GPG private key, used to sign repo.'
  local_path:
    default: './'
runs:
  using: 'docker'
  image: 'Dockerfile'
  
  env:
    repo_name: ${{ inputs.repo_name }}
    gpg_key: ${{ inputs.gpg-privatekey }}
    local_path: ${{ inputs.local_path }}
